/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ionicframework.starter;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
<<<<<<< HEAD
=======
        public static final int screen=0x7f020001;
>>>>>>> 81081e4e4e8e83deb61219409e9b92ecf55b86f2
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
    public static final class xml {
        public static final int config=0x7f030000;
    }
}
